/*#################### GET ASSET #######################*/
DROP FUNCTION IF EXISTS GET_ASSET;
DELIMITER // 
CREATE FUNCTION GET_ASSET(IN_ASSET_CODE VARCHAR(8)) 
RETURNS INT 
DETERMINISTIC
BEGIN 
	DECLARE ID INT DEFAULT NULL;
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET ID = NULL;
	
	SELECT 
		ASSET_ID INTO ID
	FROM 
		ASSET 
	WHERE 
		ASSET_CODE = IN_ASSET_CODE
    LIMIT 1;
  
    RETURN ID;
END //
DELIMITER ;

/*#################### GET_GROUP #######################*/
DROP FUNCTION IF EXISTS GET_GROUP;
DELIMITER //
CREATE FUNCTION GET_GROUP(IN_GROUP_CODE VARCHAR(20))
RETURNS INT 
DETERMINISTIC
BEGIN 
	DECLARE ID INT DEFAULT NULL;
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET ID = NULL;
	
	SELECT 
		GROUP_ID INTO ID
	FROM 
		GROUP_CLASS 
	WHERE 
		GROUP_CODE = IN_GROUP_CODE
    LIMIT 1;
  
    RETURN ID;
END //
DELIMITER ;
